### PR TITLE
Add aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Add aarch64 wheel build support.
Related to https://github.com/embotech/ecos-python/issues/23 @SteveDiamond Could you please review this PR?

### CODE REVIEW

**Comment by odidev** [comment]
The build for **arm64-graviton** is passing in **Travis-ci.com**. **Travis-ci.org** will be shutting down soon, so it would be great if you migrate the repo to **Travis-ci.com**.

**Comment by SteveDiamond** [comment]
@odidev I can't migrate this repo to travis.com. It's not giving me the option. I think the embotech organization would need to.  I can approve this change regardless though.

**Comment by odidev** [comment]
@adomahidi, what are your thoughts on migrating [ecos-python](https://github.com/embotech/ecos-python) to [travisci.com](https://www.travis-ci.com/), as [travisci.org](https://www.travis-ci.org/) will be shutting down soon.

**Comment by adomahidi** [comment]
Fine for me!

**Comment by odidev** [comment]
@adomahidi, could you please do the needful? Thanks in advance.

**Comment by adomahidi** [comment]
Done, but there's an error for aarch64. Logfile:
I don't have time to debug this, please advise

```
travis_fold:start:worker_info
[0K[33;1mWorker information[0m
hostname: b72dceba-5884-46dd-bffd-23758fdb65b9@460367.ip-10-67-27-67
version: ? ?
instance: travis-job-embotech-ecos-python-499762911 1180defdc3d09f4a62fa3ec03e2be52d4eb757b40801f4cdf581db66ec074f96 (via amqp)
startup: 2.460119771s
travis_fold:end:worker_info
[0Ktravis_time:start:293f0628
[0Ktravis_time:end:293f0628:start=1618917023451101801,finish=1618917023558925884,duration=107824083,event=no_world_writable_dirs
[0Ktravis_time:start:14370abd
[0Ktravis_time:end:14370abd:start=1618917023561936665,finish=1618917023564632840,duration=2696175,event=setup_filter
[0Ktravis_time:start:0fd93afa
[0Ktravis_time:end:0fd93afa:start=1618917023568070430,finish=1618917023577554476,duration=9484046,event=agent
[0Ktravis_time:start:21bfb1f4
[0Ktravis_time:end:21bfb1f4:start=1618917023580629059,finish=1618917023582843820,duration=2214761,event=check_unsupported
[0Ktravis_time:start:008b8558
[0Ktravis_fold:start:system_info
[0K[33;1mBuild system information[0m
Build language: ruby
Build group: edge
Build dist: xenial
Build id: 223598934
Job id: 499762911
Runtime kernel version: 5.4.0-66-generic
travis-build version: 091d532a
[34m[1mBuild image provisioning date and time[0m
Mon Nov  2 06:58:51 UTC 2020
[34m[1mOperating System Details[0m
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
[34m[1mLinux Version[0m
5.0.0-23-generic
[34m[1mGit version[0m
git version 2.7.4
[34m[1mbash version[0m
GNU bash, version 4.3.48(1)-release (aarch64-unknown-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[34m[1mGCC version[0m
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[34m[1mDocker version[0m
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Wed Oct 14 19:44:19 2020
 OS/Arch:           linux/arm64
 Experimental:      false
[34m[1mLLVM version[0m
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
[34m[1mPre-installed Ruby versions[0m
ruby-2.6.3
ruby-2.6.5
ruby-2.7.0
[34m[1mPre-installed Node.js versions[0m
v10.23.0
v12.19.0
v14.15.0
v4.9.1
v6.17.1
v8.12.0
v8.17.0
[34m[1mmysql --version[0m
mysql  Ver 14.14 Distrib 5.7.32, for Linux (aarch64) using  EditLine wrapper
[34m[1mPre-installed PostgreSQL versions[0m
9.5.23
[34m[1mRedis version[0m
redis-server 5.0.6
[34m[1mMongoDB version[0m
MongoDB 4.0.21
[34m[1mCouchDB version[0m
couchdb 1.6.0
[34m[1mmvn -version[0m
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 11.0.9, vendor: AdoptOpenJDK
Java home: /usr/lib/jvm/adoptopenjdk-11-hotspot-arm64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-23-generic", arch: "aarch64", family: "unix"
[34m[1mkiex list[0m

kiex elixirs

=* elixir-1.9.1

# => - current
# =* - current && default
#  * - default

[34m[1mphpenv versions[0m
  7.2
  7.2.34
* 7.3 (set by /home/travis/.phpenv/version)
  7.3.23
  7.4
  7.4.11
[34m[1mcomposer --version[0m
Composer version 2.0.4 2020-10-30 22:39:11
travis_fold:end:system_info
[0K
travis_time:end:008b8558:start=1618917023585825325,finish=1618917023593410980,duration=7585655,event=show_system_info
[0Ktravis_time:start:01f8636f
[0Ktravis_time:end:01f8636f:start=1618917023596569180,finish=1618917023608188677,duration=11619497,event=rm_riak_source
[0Ktravis_time:start:1627ce5a
[0Ktravis_time:end:1627ce5a:start=1618917023611274386,finish=1618917023617104713,duration=5830327,event=fix_rwky_redis
[0Ktravis_time:start:0647b514
[0Ktravis_time:end:0647b514:start=1618917023620331491,finish=1618917024221123027,duration=600791536,event=wait_for_network
[0Ktravis_time:start:063af32c
[0Ktravis_time:end:063af32c:start=1618917024224279053,finish=1618917024380118862,duration=155839809,event=update_apt_keys
[0Ktravis_time:start:0a7a2fb5
[0Ktravis_time:end:0a7a2fb5:start=1618917024383032873,finish=1618917024445319758,duration=62286885,event=fix_hhvm_source
[0Ktravis_time:start:0035fac0
[0Ktravis_time:end:0035fac0:start=1618917024448338055,finish=1618917024458219117,duration=9881062,event=update_mongo_arch
[0Ktravis_time:start:2e900704
[0Ktravis_time:end:2e900704:start=1618917024461191876,finish=1618917024509328626,duration=48136750,event=fix_sudo_enabled_trusty
[0Ktravis_time:start:0e5fcca6
[0Ktravis_time:end:0e5fcca6:start=1618917024512279453,finish=1618917024514461385,duration=2181932,event=update_glibc
[0Ktravis_time:start:2a5da7d0
[0Ktravis_time:end:2a5da7d0:start=1618917024517582187,finish=1618917024535085901,duration=17503714,event=clean_up_path
[0Ktravis_time:start:0b712068
[0Ktravis_time:end:0b712068:start=1618917024538244750,finish=1618917024541042175,duration=2797425,event=fix_mvn_settings_xml
[0Ktravis_time:start:031a9de0
[0Ktravis_time:end:031a9de0:start=1618917024544064591,finish=1618917024554202734,duration=10138143,event=no_ipv6_localhost
[0Ktravis_time:start:06cd6b1b
[0Ktravis_time:end:06cd6b1b:start=1618917024557171414,finish=1618917024559524775,duration=2353361,event=fix_etc_mavenrc
[0Ktravis_time:start:0668f751
[0Ktravis_time:end:0668f751:start=1618917024562603854,finish=1618917024565903050,duration=3299196,event=fix_wwdr_certificate
[0Ktravis_time:start:0c9d8114
[0Ktravis_time:end:0c9d8114:start=1618917024572294224,finish=1618917024598444077,duration=26149853,event=put_localhost_first
[0Ktravis_time:start:218f0457
[0Ktravis_time:end:218f0457:start=1618917024601563353,finish=1618917024604224657,duration=2661304,event=home_paths
[0Ktravis_time:start:00929ff8
[0Ktravis_time:end:00929ff8:start=1618917024607353664,finish=1618917024619781701,duration=12428037,event=disable_initramfs
[0Ktravis_time:start:09b90da8
[0Ktravis_time:end:09b90da8:start=1618917024623015741,finish=1618917024635426047,duration=12410306,event=disable_ssh_roaming
[0Ktravis_time:start:015e7e90
[0Ktravis_time:end:015e7e90:start=1618917024638608576,finish=1618917024640870696,duration=2262120,event=debug_tools
[0Ktravis_time:start:3b17b174
[0Ktravis_time:end:3b17b174:start=1618917024643829761,finish=1618917024647346431,duration=3516670,event=uninstall_oclint
[0Ktravis_time:start:0fd6bd8f
[0Ktravis_time:end:0fd6bd8f:start=1618917024650426618,finish=1618917024653574759,duration=3148141,event=rvm_use
[0Ktravis_time:start:0884fca0
[0Ktravis_time:end:0884fca0:start=1618917024656592071,finish=1618917024665268569,duration=8676498,event=rm_etc_boto_cfg
[0Ktravis_time:start:030c9114
[0Ktravis_time:end:030c9114:start=1618917024668424751,finish=1618917024671051274,duration=2626523,event=rm_oraclejdk8_symlink
[0Ktravis_time:start:002e11c0
[0Ktravis_time:end:002e11c0:start=1618917024674091863,finish=1618917024677768187,duration=3676324,event=enable_i386
[0Ktravis_time:start:2e877948
[0Ktravis_time:end:2e877948:start=1618917024680835624,finish=1618917024684753127,duration=3917503,event=update_rubygems
[0Ktravis_time:start:12cc1584
[0Ktravis_time:end:12cc1584:start=1618917024687729258,finish=1618917024692505229,duration=4775971,event=ensure_path_components
[0Ktravis_time:start:02c1c468
[0Ktravis_time:end:02c1c468:start=1618917024695588304,finish=1618917024697917829,duration=2329525,event=redefine_curl
[0Ktravis_time:start:0284a678
[0Ktravis_time:end:0284a678:start=1618917024701038360,finish=1618917024758638447,duration=57600087,event=nonblock_pipe
[0Ktravis_time:start:2aef1494
[0Ktravis_time:end:2aef1494:start=1618917024761747056,finish=1618917030796972521,duration=6035225465,event=apt_get_update
[0Ktravis_time:start:02eeeb6b
[0Ktravis_time:end:02eeeb6b:start=1618917030800250146,finish=1618917030802609931,duration=2359785,event=deprecate_xcode_64
[0Ktravis_time:start:09583e00
[0Ktravis_time:end:09583e00:start=1618917030805796037,finish=1618917030809953455,duration=4157418,event=update_heroku
[0Ktravis_time:start:05eba5e6
[0Ktravis_time:end:05eba5e6:start=1618917030813014886,finish=1618917030815320542,duration=2305656,event=shell_session_update
[0Ktravis_time:start:0afdb4ca
[0Ktravis_fold:start:docker_mtu_and_registry_mirrors
[0Ktravis_fold:end:docker_mtu_and_registry_mirrors
[0Ktravis_time:end:0afdb4ca:start=1618917030818327918,finish=1618917038126896855,duration=7308568937,event=set_docker_mtu_and_registry_mirrors
[0Ktravis_time:start:14d04e9f
[0Ktravis_fold:start:resolvconf
[0Ktravis_fold:end:resolvconf
[0Ktravis_time:end:14d04e9f:start=1618917038130037948,finish=1618917038183075001,duration=53037053,event=resolvconf
[0Ktravis_time:start:0adc7904
[0Ktravis_time:end:0adc7904:start=1618917038186949370,finish=1618917038190257148,duration=3307778,event=maven_central_mirror
[0Ktravis_time:start:1b6098cc
[0Ktravis_time:end:1b6098cc:start=1618917038193486856,finish=1618917038195745341,duration=2258485,event=maven_https
[0Ktravis_time:start:0272d7ff
[0Ktravis_fold:start:services
[0Ktravis_time:start:0fe941e8
[0K$ sudo systemctl start docker
travis_time:end:0fe941e8:start=1618917038202751499,finish=1618917038212728544,duration=9977045,event=prepare
[0Ktravis_fold:end:services
[0Ktravis_time:end:0fe941e8:start=1618917038202751499,finish=1618917041217138527,duration=3014387028,event=services
[0Ktravis_time:start:1fb2ad68
[0Ktravis_time:end:1fb2ad68:start=1618917041220414930,finish=1618917041222739154,duration=2324224,event=fix_ps4
[0Ktravis_time:start:1072831e
[0K
travis_fold:start:git.checkout
[0Ktravis_time:start:063061b6
[0K$ git clone --depth=50 --branch=master https://github.com/embotech/ecos-python.git embotech/ecos-python
Cloning into 'embotech/ecos-python'...
travis_time:end:063061b6:start=1618917041229298999,finish=1618917041623589135,duration=394290136,event=checkout
[0K$ cd embotech/ecos-python
$ git checkout -qf 8ef73834182d588d90ba432a4adf85c83b138efe
travis_fold:end:git.checkout
[0K
travis_fold:start:git.submodule
[0Ktravis_time:start:073a74b0
[0K$ git submodule update --init --recursive
Submodule 'ecos' (https://github.com/embotech/ecos.git) registered for path 'ecos'
Cloning into 'ecos'...
Submodule path 'ecos': checked out '3b98fe0376ceeeb8310a06694b0a84ac59920f3f'
travis_time:end:073a74b0:start=1618917041631829027,finish=1618917042913270233,duration=1281441206,event=checkout
[0Ktravis_fold:end:git.submodule
[0Ktravis_time:end:073a74b0:start=1618917041631829027,finish=1618917042915680192,duration=1283851165,event=checkout
[0Ktravis_time:start:04d41f35
[0K
[33;1mSetting environment variables from .travis.yml[0m
$ export DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64

travis_time:end:04d41f35:start=1618917042919014973,finish=1618917042924961500,duration=5946527,event=env
[0Ktravis_fold:start:rvm
[0Ktravis_time:start:017a26ae
[0K$ rvm use default
Using /home/travis/.rvm/gems/ruby-2.7.0
travis_time:end:017a26ae:start=1618917042933155296,finish=1618917043675214842,duration=742059546,event=setup
[0Ktravis_fold:end:rvm
[0K
travis_fold:start:ruby.versions
[0K$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [aarch64-linux]
$ rvm --version
rvm 1.29.10 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 2.1.4
$ gem --version
3.1.2
travis_fold:end:ruby.versions
[0K
travis_fold:start:install
[0Ktravis_time:start:1361caba
[0K$ if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi
Using default tag: latest
latest: Pulling from pypa/manylinux2014_aarch64
6717b8ec66cd: Pulling fs layer
bb73620682a6: Pulling fs layer
7060a8002dda: Pulling fs layer
2ee96014a3d0: Pulling fs layer
f17efaccce6d: Pulling fs layer
d5689938b9d6: Pulling fs layer
4c561405f1c9: Pulling fs layer
1b4aea6b1996: Pulling fs layer
5edc26b67669: Pulling fs layer
f1a0ca21a612: Pulling fs layer
df347c47c61f: Pulling fs layer
b90e2848d999: Pulling fs layer
2df832c6768f: Pulling fs layer
6f06b0d22b7e: Pulling fs layer
e20aa3f7296b: Pulling fs layer
cfeb333bcb26: Pulling fs layer
290ff854fe6c: Pulling fs layer
0ae6858f558b: Pulling fs layer
83430727106e: Pulling fs layer
ce111d5c0741: Pulling fs layer
8f1c0e4f29c7: Pulling fs layer
97c9d28fe347: Pulling fs layer
8dbe464c3657: Pulling fs layer
ed255b142ea0: Pulling fs layer
46cd59d3f7d8: Pulling fs layer
2ee96014a3d0: Waiting
f17efaccce6d: Waiting
d5689938b9d6: Waiting
4c561405f1c9: Waiting
1b4aea6b1996: Waiting
5edc26b67669: Waiting
f1a0ca21a612: Waiting
df347c47c61f: Waiting
b90e2848d999: Waiting
2df832c6768f: Waiting
8f1c0e4f29c7: Waiting
6f06b0d22b7e: Waiting
97c9d28fe347: Waiting
e20aa3f7296b: Waiting
8dbe464c3657: Waiting
cfeb333bcb26: Waiting
ed255b142ea0: Waiting
290ff854fe6c: Waiting
46cd59d3f7d8: Waiting
0ae6858f558b: Waiting
83430727106e: Waiting
ce111d5c0741: Waiting
7060a8002dda: Download complete
bb73620682a6: Download complete
2ee96014a3d0: Verifying Checksum
2ee96014a3d0: Download complete
f17efaccce6d: Verifying Checksum
f17efaccce6d: Download complete
d5689938b9d6: Verifying Checksum
d5689938b9d6: Download complete
1b4aea6b1996: Download complete
5edc26b67669: Verifying Checksum
5edc26b67669: Download complete
f1a0ca21a612: Download complete
df347c47c61f: Verifying Checksum
df347c47c61f: Download complete
b90e2848d999: Download complete
2df832c6768f: Verifying Checksum
2df832c6768f: Download complete
6f06b0d22b7e: Verifying Checksum
6f06b0d22b7e: Download complete
e20aa3f7296b: Verifying Checksum
e20aa3f7296b: Download complete
cfeb333bcb26: Verifying Checksum
cfeb333bcb26: Download complete
290ff854fe6c: Verifying Checksum
290ff854fe6c: Download complete
0ae6858f558b: Download complete
83430727106e: Verifying Checksum
83430727106e: Download complete
ce111d5c0741: Verifying Checksum
ce111d5c0741: Download complete
6717b8ec66cd: Verifying Checksum
6717b8ec66cd: Download complete
8f1c0e4f29c7: Verifying Checksum
8f1c0e4f29c7: Download complete
97c9d28fe347: Verifying Checksum
97c9d28fe347: Download complete
ed255b142ea0: Verifying Checksum
ed255b142ea0: Download complete
46cd59d3f7d8: Verifying Checksum
46cd59d3f7d8: Download complete
4c561405f1c9: Verifying Checksum
4c561405f1c9: Download complete
8dbe464c3657: Verifying Checksum
8dbe464c3657: Download complete
6717b8ec66cd: Pull complete
bb73620682a6: Pull complete
7060a8002dda: Pull complete
2ee96014a3d0: Pull complete
f17efaccce6d: Pull complete
d5689938b9d6: Pull complete
4c561405f1c9: Pull complete
1b4aea6b1996: Pull complete
5edc26b67669: Pull complete
f1a0ca21a612: Pull complete
df347c47c61f: Pull complete
b90e2848d999: Pull complete
2df832c6768f: Pull complete
6f06b0d22b7e: Pull complete
e20aa3f7296b: Pull complete
cfeb333bcb26: Pull complete
290ff854fe6c: Pull complete
0ae6858f558b: Pull complete
83430727106e: Pull complete
ce111d5c0741: Pull complete
8f1c0e4f29c7: Pull complete
97c9d28fe347: Pull complete
8dbe464c3657: Pull complete
ed255b142ea0: Pull complete
46cd59d3f7d8: Pull complete
Digest: sha256:26156691e1e7c3ddcd93633df117e0c93fdff3fb959b2e6fd7683471bb928974
Status: Downloaded newer image for quay.io/pypa/manylinux2014_aarch64:latest
travis_time:end:1361caba:start=1618917044229593259,finish=1618917056831743656,duration=12602150397,event=install
[0Ktravis_fold:end:install
[0Ktravis_time:start:025ad8c0
[0K$ make version
travis_time:end:025ad8c0:start=1618917056835650353,finish=1618917056892602259,duration=56951906,event=script
[0K[32;1mThe command "make version" exited with 0.[0m
travis_time:start:13461130
[0K$ if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh; fi
++ uname -m
+ '[' aarch64 == aarch64 ']'
+ yum install -y blas-devel lapack-devel
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: d36uatko69830t.cloudfront.net
 * centos-sclo-rh: d36uatko69830t.cloudfront.net
 * extras: d36uatko69830t.cloudfront.net
 * updates: d36uatko69830t.cloudfront.net
Resolving Dependencies
--> Running transaction check
---> Package blas-devel.aarch64 0:3.4.2-8.el7 will be installed
--> Processing Dependency: blas(aarch-64) = 3.4.2-8.el7 for package: blas-devel-3.4.2-8.el7.aarch64
--> Processing Dependency: gcc-gfortran for package: blas-devel-3.4.2-8.el7.aarch64
--> Processing Dependency: libblas.so.3()(64bit) for package: blas-devel-3.4.2-8.el7.aarch64
---> Package lapack-devel.aarch64 0:3.4.2-8.el7 will be installed
--> Processing Dependency: lapack(aarch-64) = 3.4.2-8.el7 for package: lapack-devel-3.4.2-8.el7.aarch64
--> Processing Dependency: liblapacke.so.3()(64bit) for package: la

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated

```

**Comment by odidev** [comment]
I have run the build on travis-ci.com and the arm64 build is passing successfully.

**Travis-ci Logs** - https://travis-ci.com/github/odidev/ecos-python/builds/223701473 

Could you please re-trigger the build and if it still fails, I will look into it.

**Comment by adomahidi** [comment]
yeap looking good - so all set here, right?

**Comment by odidev** [comment]
Yes, I think retriggering the build will solve the problem.

**Pull request merged**
